pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
    sudo add-apt-repository ppa:jonathonf/gcc -y
    sudo apt-get -qq update
  displayName: 'Add GCC Repository'
  continueOnError: false

- script: |
    sudo apt-get install -y build-essential software-properties-common
    sudo apt-get install -y gcc-8
    sudo apt-get install -y g++ mingw-w64 libgmp-dev bison
    sudo apt-get install -y libmpfr-dev libmpc-dev
    sudo apt-get install -y byacc texinfo
    sudo apt-get install -y zip gzip tar
  displayName: 'Install Required Packages'
  continueOnError: false

- bash: |
    cd $BUILD_SOURCESDIRECTORY
    touch "CHANGELOG.txt"
    git log --oneline --decorate > CHANGELOG.txt
  displayName: 'Create Changelog'
  continueOnError: false

- script: |
    bash ./build.sh
  displayName: 'Build Project'
  continueOnError: false

- bash: |
    mkdir -p $BUILD_ARTIFACTSTAGINGDIRECTORY/linux64/
    mv "$BUILD_SOURCESDIRECTORY/scripts/build/gcc-toolchain-mips64-linux64.tar.gz" "$BUILD_ARTIFACTSTAGINGDIRECTORY/linux64/"
    mkdir -p $BUILD_ARTIFACTSTAGINGDIRECTORY/win64/
    mv "$BUILD_SOURCESDIRECTORY/scripts/build/gcc-toolchain-mips64-win64.zip" "$BUILD_ARTIFACTSTAGINGDIRECTORY/win64/"
  displayName: 'Move Artifacts to Staging Directory'
  continueOnError: false

# Publish build artifacts to Azure Artifacts/TFS or a file share
- task: PublishBuildArtifacts@1
  displayName: Publish Build Artifacts
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'binaries' 
    publishLocation: 'Container' # Options: container, filePath
    #targetPath: # Required when publishLocation == FilePath
    parallel: true # Optional
    #parallelCount: # Optional

#- task: AzureFileCopy@3
#  inputs:
#    sourcePath: '$(Build.ArtifactStagingDirectory)\*.zip'
#    azureSubscription: 'MsdnAzureServiceRole'
#    Destination: 'AzureBlob'
#    storage: 'n64tools'
#    ContainerName: 'binaries'
#    blobPrefix: 'N64-tools/mips64-gcc-toolchain/$(Build.SourceBranchName)/latest/'
#    outputStorageUri: 'outputStorageUri'
#  displayName: Upload program to Blob storage
  #condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

  - task: AzureCLI@1
    inputs:
      connectedServiceNameARM: 'MsdnAzureServiceRole'
      scriptLocation: 'inlineScript'
      inlineScript: 'AzCopy /Source:$(Build.ArtifactStagingDirectory) /Dest:https://n64tools.blob.core.windows.net/N64-tools/mips64-gcc-toolchain/$(Build.SourceBranchName)/latest/ /Pattern:"gcc-toolchain-mips64-linux64.tar.gz"'
    displayName: Upload linux binary to Blob storage

  - task: AzureCLI@1
    inputs:
      connectedServiceNameARM: 'MsdnAzureServiceRole'
      scriptLocation: 'inlineScript'
      inlineScript: 'AzCopy /Source:$(Build.ArtifactStagingDirectory) /Dest:https://n64tools.blob.core.windows.net/N64-tools/mips64-gcc-toolchain/$(Build.SourceBranchName)/latest/ /Pattern:"gcc-toolchain-mips64-win64.zip"'
    displayName: Upload windows binary to Blob storage